version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: srs_db
      MYSQL_USER: srs_db
      MYSQL_PASSWORD: srs_passwd
    volumes:
      - "../conf/mysql:/etc/mysql/conf.d"
    ports:
      - "127.0.0.1:3308:3308"
  srs:
    build: ../
    image: shopping-rest-service
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_PASSWORD: srs_passwd
    depends_on:
      - db
    links:
      - db:mysql
    ports:
      - "8080"
